project:
  type: website
website:
  # page-footer:
  #   left: "This page is built with ❤️ and [Quarto](https://quarto.org/)."
  # margin-header: suscribe.html
  # cookie-consent:
  #   type: express
  #   style: headline
  #   palette: dark
  back-to-top-navigation: true
  google-analytics:
    tracking-id: "G-2QCYBRDYFQ"
    anonymize-ip: true
  title: ""
  favicon: iconoxd.png
  navbar:
    logo: logo_eps2.png
    collapse-below: sm
    right:
      - Presentación.qmd
      # - Datos de monitoreo.qmd
      - monitoreo_beta.qmd
      - noticias.qmd
      - icon: instagram
        href: https://www.instagram.com/mrse.epsilo/
      - icon: twitter
        href: https://twitter.com
format:
  html:
    theme: flatly
    css: styles.css
editor: visual

